### ISSUE TITLE
Readable url

### ISSUE THREAD

**Issue by andrezaycev** [snagles/docker-registry-manager#149]
When i connect manager in stack i use registry:5000 url. But external url using over proxy- registry.example.com

Can you add variable for view readable url?

![image](https://user-images.githubusercontent.com/9984761/37785685-259c6316-2e3e-11e8-91a2-8b97133a8c5d.png)

**Comment by snagles** [comment]
Hi,

I'm a bit confused on what you're asking for here, is the issue the spacing where you can't see the entire URL or the issue the URL that is shown is the "non-proxy" URL?

**Comment by andrezaycev** [comment]
I'm use docker-compose and short names in network
For example:
 facticially address for registry http://registry:5000

but world use it as https://registry.example.com

Other frontend soft ussually have additional variable for mask it, for correct showing in web-page

**Comment by avonderluft** [comment]
Hi snagles.  Great work here!  I'm not sure if my request is the same as andrezaycev's, but I would like to be able to copy/paste from the docker Pull action to my terminal, in order to actually pull an image.  Since YAML does not allow periods in keys, I can't make the name of the repo in registries.yml match.

e.g. I have the registry name myregistry-np with the URL https://myregistry-np.us . In this scenario I would like the the Pull action to show `docker pull myregistry-np.us/myimage:tag  so that I can just copy/paste it and run it.  Make sense?

**Comment by snagles** [comment]
Fixed in #149
