### ISSUE TITLE
Webserver Hanging

### ISSUE THREAD

**Issue by Annihil8ted** [snagles/docker-registry-manager#162]
I seem to have issues persisting the webserver. After container creation, everything performs smoothly but in about 10 minutes of so, I no longer am able to get any response from the server

**Comment by Annihil8ted** [comment]
Hmm more specifically the Repositories, Registries, and Dashboard panes

**Comment by pavlovpetr** [comment]
Hi, 
I had the same issues, and i noticed that it happens when the registry manager cannot to reach the Local Registry. 
You can check it run "docker logs -f (or --tail 20) name_of_you_regmanager" 
You'll see something like below:
`level=fatal msg="Failed to create registry (http://192.168.36.37): Get http://192.168.36.37:5000/v2/: dial tcp 192.168.36.37:5000: connect: connection refused" file=registry.go line=295 source=app`
It started when I installed windows updates (one of my registries runs on windows). The next windows updates fixed the issue.

**Comment by ruanton29** [comment]
I have the same issues. After 10 min it's stop responding  =(

**Comment by pietervogelaar** [comment]
Same here. After clicking a bit in the GUI, the application hangs within one minute.

**Comment by luisxiaomai** [comment]
same issue

**Comment by pietervogelaar** [comment]
This app even caused network connectivity problems in our cluster, so be careful with it!

**Comment by oleksii-shyman** [comment]
https://github.com/snagles/docker-registry-manager/pull/176
I've created this pull-request, that hopefully would be merged (Otherwise -> feel free to apply the patch manually)
It solved application GUI hangs for 2+ minutes in our case.

**Comment by snagles** [comment]
Fixed in #176 as mentioned above
